name: Build MediaControlTweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 设置 JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: chmod +x gradlew
      - run: ./gradlew assembleDebug  # 生成 debug APK
      - name: 列出构建目录
        run: ls -R app/build/outputs/apk/  # 递归列出所有 APK 路径
      - name: 上传 APK 到 Releases
        uses: svenstaro/upload-release-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/apk/debug/*.apk  # 通配符需 action 支持
          tag: ${{ github.ref }}
